# Generated by Django 3.2.9 on 2021-11-24 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resale', '0003_auto_20211124_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacter',
            options={'ordering': ('name',), 'verbose_name': 'manufacter', 'verbose_name_plural': 'manufacters'},
        ),
    ]
