# Generated by Django 3.2.9 on 2021-11-24 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resale', '0004_alter_manufacter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='manufacter',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={},
        ),
        migrations.AlterIndexTogether(
            name='vehicle',
            index_together=set(),
        ),
    ]
